author: "Wojtek Gumuła"
default_title: "My personal site and more"
description: "Random bits and pieces"
email: "wojtek@wgml.pl"
headline: "cat /etc/profile"
repository_url: "https://github.com/wgml/wgml.github.io"
site_url: "wgml.pl"
title: "[wgml.pl]"
url: "https://wgml.pl"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      tags: ["personal", "dev", "web", "blog", "cpp"]
      navbar:
        -
          url: "/"
          name: "root"
        -
          url: "/about.html"
          name: "about"
        -
          url: "/files/resume.pdf"
          name: "resume"
          args: "target=\"_blank\""
        -
          url: "https://github.com/wgml"
          name: "github"
          args: "target=\"_blank\""
        -
          url: "/feed.xml"
          name: "feed"
highlighter: none
markdown: kramdown
permalink: /blog/:title.html
sass:
  style: compressed
