defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      site_url: "wgml.pl"
      author: "Wojtek Gumuła"
      email: "me@wgml.pl"
      repository_url: "https://github.com/wgml/wgml.github.io"
      title: "cat /etc/profile"
      tags: ["personal", "dev", "web", "blog", "cpp"]
      navbar:
        -
          url: "/"
          name: "root"
        -
          url: "/about.html"
          name: "about"
        -
          url: "/files/resume.pdf"
          name: "resume"
          args: "target=\"_blank\""
        -
          url: "https://github.com/wgml"
          name: "github"
          args: "target=\"_blank\""
highlighter: rouge
markdown: kramdown
permalink: /blog/:title.html
kramdown:
  syntax_highlighter_opts:
    disable : true
sass:
  style: compressed
plugins:
  - liquid_reading_time
  - liquid_pluralize
